### ISSUE TITLE
Completar columnas en Blanco y poner un link a la página anterior

### ISSUE THREAD

**Issue by fonsecareyna82** [ramlunak/ceuopenmed#51]
---------------------------------------------------------------------------------------------------------
Completar las siguientes columnas con sus respectivos valores(en algunos casos falta hasta la columna):
---------------------------------------------------------------------------------------------------------
  **Columna**: Tipo de Entidad, Fuerza, Comentario
  **Vista**      :  Asociaciones (como profesor)  

 **Columna**: Tipo de Entidad, Fuerza, Comentario
  **Vista**      :  Asociaciones (como estudiante)  

---------------------------------------------------------------------------------------------------------
Poner un botón para ir a la página anterior en las siguientes vistas:
---------------------------------------------------------------------------------------------------------
- Crear asociaciones (profesores y estudiantes)

**Comment by ramlunak** [comment]
ok
